<?php
require_once __DIR__.'/bootstrap.php';
function catalog_page(array $types=[], string $heading='Anime Catalog', string $description='Discover anime on AniRead.'): void {
 global $pdo; $page=valid_page(); $per=24; $where=[]; $params=[];
 if($types){$where[]='a.type IN ('.implode(',',array_fill(0,count($types),'?')).')';$params=array_merge($params,$types);}
 foreach(['type','status','season'] as $f){if(isset($_GET[$f])&&$_GET[$f]!==''){if($f==='type'&&$types)continue;$where[]="a.$f=?";$params[]=$_GET[$f];}}
 if(isset($_GET['year'])&&ctype_digit((string)$_GET['year'])&&strlen((string)$_GET['year'])===4){$where[]='a.year=?';$params[]=(int)$_GET['year'];}
 if(!empty($_GET['genre'])&&ctype_digit((string)$_GET['genre'])){$where[]='EXISTS (SELECT 1 FROM anime_genres agf WHERE agf.anime_id=a.id AND agf.genre_id=?)';$params[]=(int)$_GET['genre'];}
 if(($q=trim((string)($_GET['q']??'')))!==''){$where[]='(a.title LIKE ? OR a.english_title LIKE ? OR a.japanese_title LIKE ?)';$like="%$q%";array_push($params,$like,$like,$like);}
 $allowed=['rating'=>'a.score DESC','popularity'=>'a.popularity IS NULL,a.popularity ASC','recent'=>'a.created_at DESC','title'=>'a.title ASC'];$sort=$allowed[$_GET['sort']??'popularity']??$allowed['popularity'];$w=$where?' WHERE '.implode(' AND ',$where):'';
 $c=$pdo->prepare("SELECT COUNT(*) FROM anime a$w");$c->execute($params);$pages=max(1,(int)ceil((int)$c->fetchColumn()/$per));$page=min($page,$pages);$s=$pdo->prepare("SELECT a.* FROM anime a$w ORDER BY $sort LIMIT ? OFFSET ?");foreach($params as $i=>$v)$s->bindValue($i+1,$v);$s->bindValue(count($params)+1,$per,PDO::PARAM_INT);$s->bindValue(count($params)+2,($page-1)*$per,PDO::PARAM_INT);$s->execute();$items=$s->fetchAll();
 $title=$heading.' — AniRead';$GLOBALS['description']=$description;include __DIR__.'/includes/header.php';?><h1><?=e($heading)?></h1><form class="filters"><input class="input" name="q" value="<?=e($_GET['q']??'')?>" placeholder="Search title"><select name="type"><option value="">All types</option><?php foreach(['TV','Movie','OVA','ONA','Special'] as $x):?><option value="<?=$x?>" <?=($_GET['type']??'')===$x?'selected':''?>><?=$x?></option><?php endforeach;?></select><select name="status"><option value="">All statuses</option><?php foreach(['Currently Airing','Finished Airing','Not yet aired'] as $x):?><option <?=($_GET['status']??'')===$x?'selected':''?>><?=$x?></option><?php endforeach;?></select><input class="input" name="year" inputmode="numeric" maxlength="4" placeholder="Year" value="<?=e($_GET['year']??'')?>"><select name="season"><option value="">All seasons</option><?php foreach(['winter','spring','summer','fall'] as $x):?><option <?=($_GET['season']??'')===$x?'selected':''?>><?=$x?></option><?php endforeach;?></select><select name="sort"><option value="popularity">Popularity</option><option value="rating" <?=($_GET['sort']??'')==='rating'?'selected':''?>>Rating</option><option value="recent" <?=($_GET['sort']??'')==='recent'?'selected':''?>>Recently added</option><option value="title" <?=($_GET['sort']??'')==='title'?'selected':''?>>Title</option></select><button class="btn">Filter</button></form><?php if(!$items):?><div class="form"><h2>No anime found</h2><p class="muted">Try a different filter or synchronize metadata from the admin panel.</p></div><?php else:?><div class="grid"><?php foreach($items as $a)card($a);?></div><?php $query=$_GET;unset($query['page']);page_links($page,$pages,'?'.http_build_query($query));endif;include __DIR__.'/includes/footer.php';}
if(isset($_GET['id'])){require __DIR__.'/anime-detail.php';exit;}catalog_page();
