ALTER TABLE episodes ADD COLUMN IF NOT EXISTS thumbnail TEXT NULL, ADD COLUMN IF NOT EXISTS active TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE sync_logs ADD COLUMN IF NOT EXISTS finished_at TIMESTAMP NULL, ADD COLUMN IF NOT EXISTS records_added INT NOT NULL DEFAULT 0, ADD COLUMN IF NOT EXISTS records_updated INT NOT NULL DEFAULT 0, ADD COLUMN IF NOT EXISTS errors INT NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS languages(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(80) NOT NULL UNIQUE,active TINYINT(1) NOT NULL DEFAULT 1) ENGINE=InnoDB;
INSERT IGNORE INTO languages(name) VALUES ('Japanese SUB'),('English SUB'),('English DUB'),('Hindi DUB'),('Bengali DUB'),('Tamil DUB'),('Telugu DUB'),('Malayalam DUB'),('Kannada DUB'),('Other');
